import os
from datetime import datetime

REPORTS_PATH = os.path.join(os.path.dirname(__file__), '..', 'logs')

def generate_report(alert_text: str, result: dict) -> str:
    """Generates a markdown incident report and saves it to logs folder"""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"incident_report_{timestamp}.md"
    filepath = os.path.join(REPORTS_PATH, filename)

    report = f"""# Incident Report
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Alert Details
{alert_text.strip()}

## Triage Summary
| Field | Value |
|-------|-------|
| Severity | {result.get('severity')} |
| Confidence | {result.get('confidence')} |
| MITRE Tactic | {result.get('mitre_tactic')} |
| MITRE Technique | {result.get('mitre_technique')} |
| Additional Techniques | {result.get('additional_techniques')} |

## Analysis
{result.get('summary')}

## Immediate Action
{result.get('immediate_action')}

## Investigation Steps
{result.get('investigation_steps')}

## False Positive Check
{result.get('false_positive_check')}

---
*Report generated by AI-Powered SOC Alert Triage Assistant*
"""

    with open(filepath, 'w') as f:
        f.write(report)

    return filepath